//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using CapaEntidades;
    public partial class SABER_DBEntities : DbContext
    {
        public SABER_DBEntities()
            : base("name=SABER_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<INCORRECTA_EXPLICACION> INCORRECTA_EXPLICACION { get; set; }
        public DbSet<PREGUNTA> PREGUNTAS { get; set; }
        public DbSet<RESPUESTA> RESPUESTAS { get; set; }
    }
}
